global.WALL_RADIUS = 1020;
var ROOM_CIRCUMFERENCE = pi * global.WALL_RADIUS * 2;
var LADDER_WIDTH_PIXELS = 80;
global.LADDER_WIDTH = LADDER_WIDTH_PIXELS/ROOM_CIRCUMFERENCE * 360;
global.LEDGE_TOLERANCE = 5;